// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrienteeringApi.Database;

namespace OrienteeringApi.Migrations
{
    [DbContext(typeof(OrienteeringContext))]
    [Migration("20210210145015_SeedControls")]
    partial class SeedControls
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("OrienteeringApi.Database.Control", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Controls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 2, 10, 14, 50, 14, 986, DateTimeKind.Local).AddTicks(6001),
                            Description = "A very well hidden control",
                            Image = "image1",
                            Modified = new DateTime(2021, 2, 10, 14, 50, 14, 986, DateTimeKind.Local).AddTicks(6001)
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2021, 2, 10, 14, 50, 14, 986, DateTimeKind.Local).AddTicks(6001),
                            Description = "A well placed control",
                            Image = "image2",
                            Modified = new DateTime(2021, 2, 10, 15, 0, 14, 986, DateTimeKind.Local).AddTicks(6001)
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2021, 2, 10, 14, 50, 14, 986, DateTimeKind.Local).AddTicks(6001),
                            Description = "Behind the bike rack",
                            Image = "image3",
                            Modified = new DateTime(2021, 2, 10, 15, 10, 14, 986, DateTimeKind.Local).AddTicks(6001)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
