// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrienteeringApi.Database;

namespace OrienteeringApi.Migrations
{
    [DbContext(typeof(OrienteeringContext))]
    [Migration("20210210202912_SeedControls2")]
    partial class SeedControls2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("OrienteeringApi.Database.Control", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Controls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 2, 10, 20, 29, 11, 666, DateTimeKind.Local).AddTicks(8603),
                            Description = "A very well hidden control",
                            Image = "image1",
                            Modified = new DateTime(2021, 2, 10, 20, 29, 11, 666, DateTimeKind.Local).AddTicks(8603)
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2021, 2, 10, 20, 29, 11, 666, DateTimeKind.Local).AddTicks(8603),
                            Description = "A well placed control",
                            Image = "image2",
                            Modified = new DateTime(2021, 2, 10, 20, 39, 11, 666, DateTimeKind.Local).AddTicks(8603)
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2021, 2, 10, 20, 29, 11, 666, DateTimeKind.Local).AddTicks(8603),
                            Description = "Behind the bike rack",
                            Image = "image3",
                            Modified = new DateTime(2021, 2, 10, 20, 49, 11, 666, DateTimeKind.Local).AddTicks(8603)
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2021, 2, 10, 20, 29, 11, 666, DateTimeKind.Local).AddTicks(8603),
                            Description = "On a wall",
                            Image = "image4",
                            Modified = new DateTime(2021, 2, 10, 20, 59, 11, 666, DateTimeKind.Local).AddTicks(8603)
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2021, 2, 10, 20, 29, 11, 666, DateTimeKind.Local).AddTicks(8603),
                            Description = "Under a hat",
                            Image = "image5",
                            Modified = new DateTime(2021, 2, 10, 21, 9, 11, 666, DateTimeKind.Local).AddTicks(8603)
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2021, 2, 10, 20, 29, 11, 666, DateTimeKind.Local).AddTicks(8603),
                            Description = "In a room",
                            Image = "image6",
                            Modified = new DateTime(2021, 2, 10, 21, 19, 11, 666, DateTimeKind.Local).AddTicks(8603)
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2021, 2, 10, 20, 29, 11, 666, DateTimeKind.Local).AddTicks(8603),
                            Description = "On the rrof",
                            Image = "image7",
                            Modified = new DateTime(2021, 2, 10, 21, 29, 11, 666, DateTimeKind.Local).AddTicks(8603)
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2021, 2, 10, 20, 29, 11, 666, DateTimeKind.Local).AddTicks(8603),
                            Description = "Behind the curtain",
                            Image = "image8",
                            Modified = new DateTime(2021, 2, 10, 21, 39, 11, 666, DateTimeKind.Local).AddTicks(8603)
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2021, 2, 10, 20, 29, 11, 666, DateTimeKind.Local).AddTicks(8603),
                            Description = "Behind you!",
                            Image = "image9",
                            Modified = new DateTime(2021, 2, 10, 21, 49, 11, 666, DateTimeKind.Local).AddTicks(8603)
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2021, 2, 10, 20, 29, 11, 666, DateTimeKind.Local).AddTicks(8603),
                            Description = "In pla",
                            Image = "image10",
                            Modified = new DateTime(2021, 2, 10, 21, 59, 11, 666, DateTimeKind.Local).AddTicks(8603)
                        });
                });

            modelBuilder.Entity("OrienteeringApi.Database.LessonControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Answer")
                        .HasColumnType("text");

                    b.Property<int>("ControlId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LessonGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("MapId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Question")
                        .HasColumnType("text");

                    b.Property<int>("XPos")
                        .HasColumnType("integer");

                    b.Property<int>("YPos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LessonControls");
                });

            modelBuilder.Entity("OrienteeringApi.Database.LessonGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AgeGroup")
                        .HasColumnType("text");

                    b.Property<string>("Conclusion")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Equipment")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GameBasedLearning")
                        .HasColumnType("text");

                    b.Property<string>("Intro")
                        .HasColumnType("text");

                    b.Property<int>("LessonSubjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MainSession")
                        .HasColumnType("text");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Shared")
                        .HasColumnType("boolean");

                    b.Property<string>("Warmup")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LessonGroups");
                });

            modelBuilder.Entity("OrienteeringApi.Database.LessonSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LessonSubjects");
                });

            modelBuilder.Entity("OrienteeringApi.Database.Map", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Maps");
                });
#pragma warning restore 612, 618
        }
    }
}
